name: two_eight_two
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.2+57 # Update this version number when you release a new version

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  google_maps_flutter: ^2.14.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  sign_in_with_apple: ^7.0.1
  flutter_markdown: ^0.7.7+1
  font_awesome_flutter: ^10.12.0
  google_sign_in: ^7.2.0
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  dotted_border: ^3.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  sentry_flutter: ^9.8.0
  http: ^1.6.0
  package_info_plus: ^9.0.0
  rate_my_app: ^2.3.2
  readmore: ^3.0.0
  confetti: ^0.8.0
  sliding_up_panel: ^2.0.0+1
  firebase_remote_config: ^6.1.1
  mixpanel_flutter: ^2.4.4
  flutter_branch_sdk: ^8.10.0
  share_plus: ^12.0.1
  mapbox_maps_flutter: ^2.12.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/app_icon.png"
  android: true
  ios: true

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  flavors:
    prod:
      android: true
      ios: true
      image_path: "assets/icons/app_icon.png"
      adaptive_icon_background: "#ffffff"
      adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
    dev:
      android: true
      ios: true
      image_path: "assets/icons/app_icon.png"
      adaptive_icon_background: "#ffffff"
      adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/documents/
    - assets/weather/
    - assets/icons/
    - assets/branch-config.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
